apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: apis-gateway
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    istio: ingressgateway-apis
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - "*"
    {{- if .Values.cortex.ssl_certificate_arn }}
    - port:
        number: 443
        name: https
        protocol: HTTP
      hosts:
        - "*"
    {{- else if .Values.networking.api-ingress.gateways.istio-ingressgateway.tls_secret }}
    - port:
        number: 443
        name: https
        protocol: HTTPS
      hosts:
        - "*"
      tls:
        mode: SIMPLE
        serverCertificate: /etc/istio/ingressgateway-certs/tls.crt
        privateKey: /etc/istio/ingressgateway-certs/tls.key
    {{- end }}
