apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: "cortex-{{ .Values.cortex.cluster_name }}-{{ .Release.Namespace }}"
volumeBindingMode: WaitForFirstConsumer
{{- if eq .Values.global.provider "aws" }}
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2
{{- else if eq .Values.global.provider "gcp" }}
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-ssd
{{- end }}
