global:
  provider: ""

  # Default hub for Istio images.
  # Releases are published to docker hub under 'istio' project.
  # Dev builds from prow are on gcr.io
  hub: quay.io/cortexlabs

  # Default tag for Istio images.
  tag: master # CORTEX_VERSION

  # Image for the proxy controller
  proxy:
    image: istio-proxy

cortex:
  # Please provide the following required fields for a cortex installation on AWS
  cluster_name: ""
  bucket: "" # e.g. "my-cortex-bucket" (without s3:// or gs://)

  # AWS only
  region: ""

  # GCP only
  zone: ""
  project: ""

  # CORTEX_VERSION
  image_operator: quay.io/cortexlabs/operator:master
  image_manager: quay.io/cortexlabs/manager:master
  image_downloader: quay.io/cortexlabs/downloader:master
  image_request_monitor: quay.io/cortexlabs/request-monitor:master
  image_cluster_autoscaler: quay.io/cortexlabs/cluster-autoscaler:master
  image_metrics_server: quay.io/cortexlabs/metrics-server:master
  image_inferentia: quay.io/cortexlabs/inferentia:master
  image_neuron_rtd: quay.io/cortexlabs/neuron-rtd:master
  image_nvidia: quay.io/cortexlabs/nvidia:master
  image_fluent_bit: quay.io/cortexlabs/fluent-bit:master
  image_istio_proxy: quay.io/cortexlabs/istio-proxy:master
  image_istio_pilot: quay.io/cortexlabs/istio-pilot:master
  image_google_pause: quay.io/cortexlabs/pause:master
  image_prometheus: quay.io/cortexlabs/prometheus:master
  image_prometheus_config_reloader: quay.io/cortexlabs/prometheus-config-reloader:master
  image_prometheus_operator: quay.io/cortexlabs/prometheus-operator:master
  image_prometheus_statsd_exporter: quay.io/cortexlabs/prometheus-statsd-exporter:master
  image_grafana: quay.io/cortexlabs/grafana:master

  resources:
    requests:
      cpu: 200m
      memory: 128Mi
    limits:
      cpu: 2000m
      memory: 1024Mi

networking:
  api-ingress:
    gateways:
      istio-ingressgateway:
        type: LoadBalancer
        externalTrafficPolicy: Cluster
        serviceAnnotations: {}

  operator-ingress:
    gateways:
      istio-ingressgateway:
        type: LoadBalancer
        externalTrafficPolicy: Cluster
        serviceAnnotations: {}

  istio-discovery:
    pilot:
      hub: quay.io/cortexlabs
      tag: master # CORTEX_VERSION

      # Can be a full hub/image:tag
      image: istio-pilot


storageType:
  name: ssd
  awsType: gp2
  gcpType: pd-ssd

prometheus:
  volumeClaimSize: 40GB
  retentionSize: 35GB
  retentionWindow: 2w

  monitorResources:
    requests:
      cpu: null
      memory: 400Mi
    limits:
      cpu: null
      memory: null
  operatorResources:
    requests:
      cpu: 100m
      memory: 100Mi
    limits:
      cpu: 200m
      memory: 200Mi

prometheusStatsDExporter:
  resources:
    requests:
      cpu: 100m
      memory: 100Mi
    limits:
      cpu: null
      memory: 100Mi

addons:
  grafana:
    enabled: true
    resources:
      requests:
        cpu: 100m
        memory: 100Mi
      limits:
        cpu: 200m
        memory: 200Mi
      storage: 2Gbi

  fluentbit:
    enabled: true
    resources:
      requests:
        cpu: 100m
        memory: 150Mi
      limits:
        cpu: null
        memory: 150Mi
    # dataOutputConf: |
    #   [OUTPUT]
    #       Name              cloudwatch
    #       Match             k8s_container.*
    #       region            {{ .Values.cortex.region }}
    #       log_group_name    {{ .Values.cortex.cluster_name }}
    #       log_stream_prefix kube.
    #       auto_create_group true

  kubeMetricsServer:
    enabled: false
